/**
 * REVISION: 2026-03-18_V1.5
 * SOURCE: Cedar Mill Coaching Compendium (CMCC)
 * STATUS: FULL RE-AUDIT & MERGED RESTORATION
 * ACTION: Restoring all missing sections from Book I, II, and III.
 */

const coachingData = {
  // --- BOOK I: THE SEASON PLAYBOOK (MANAGEMENT) ---
  "B1-S1": { 
    book: "Book I", section: "1. Modern Philosophy", title: "1.1 Collaborative Practices", 
    content: "### 1.1 The \"Joint Practice\" Standard\n\n**The Goal**: To maximize repetitions and foster a professional league culture between opposing teams.\n\n**Execution**: \n- **Partner Up**: Schedule 60 minutes of joint drill-stations with your opponent before the game starts.\n- **The Scrimmage**: Conclude with a 45-minute developmental, coach-pitched scrimmage. \n- **Mentor Flow**: Shared field time allows veteran coaches to mentor newer coaches on-the-fly.\n\n**The Coaching Why**: We are one league, not two enemies. Joint practices eliminate \"standing around\" and double the total reps each player gets during the time block." 
  },
  "B1-S2": { 
    book: "Book I", section: "2. Staffing", title: "2.1 Building Your Staff", 
    content: "### 2.1 The \"CEO\" Staffing Model\n\n**The Goal**: To eliminate single-point-of-failure coaching and ensure every player gets active eyes on them at all times.\n\n**The Roles**:\n- **The CEO (Head Coach)**: Your primary job is the **Practice Plan**. You own the rhythm of the field and delegating station-leads.\n- **The Strategist (Bench Coach)**: Leads the dugout. Manages the \"Next Up\" flow and in-game defensive adjustments.\n- **The Instructors (Assistant Coaches)**: These are your Station Leads. They focus 100% on the mechanics of their specific drill (e.g., The Battery or Hitting).\n- **The Logistics Lead (Team Parent)**: Owns GameChanger, snack schedules, and parent CCs. This protector of the coach's time allows you to focus purely on the kids.\n\n**The Coaching Why**: When a head coach tries to do everything, they notice nothing. Delegation allows the Head Coach to \"roam\" and provide high-level feedback to individual players." 
  },
  "B1-S4": { 
    book: "Book I", section: "4. Communication", title: "4.1 The First 24 Hours", 
    content: "### 4.1 The \"First 24-Hours\" Call Strategy\n\n**The Goal**: To create an immediate personal bond with the player and reduce \"First Day\" anxiety.\n\n**The Execution**:\n- **Method**: A voice phone call directly to the player. No texts, no mass emails.\n- **The Player Script**: \"Hi, is [Player's Name] available? This is your new baseball coach! I am so excited to have you on the [Team Name] this year. I've heard great things about your [hustle/energy/swing] and I can't wait to see you at our first practice on [Field] at [Time].\"\n- **The Parent Wrap-up**: Once the player is finished, briefly confirm the time/location with the parent and ask: \"Is there anything specifically I should know about [Player's Name] to help them have the best season possible?\"\n\n**The Coaching Why**: This is your first \"win\" of the season. When a child hears a coach is specifically excited about *them*, their effort levels double before they even step on the field." 
  },
  "B1-S5": { 
    book: "Book I", section: "5. Meetings", title: "5.1 The Parent Meeting", 
    content: "### 5.1 The 15-Minute Parent Power-Meeting\n\n**The Goal**: To align parents with the team's culture and prevent sidebar drama before it starts.\n\n**The Execution**:\n- **Context**: Hold this on the grass 15 minutes *before* the end of your first practice while the kids are still drilling.\n- **The 5-Point Agenda**:\n  1. **Intro**: Your baseball background and your \"Why\" for coaching.\n  2. **The Goal**: \"We are here to make them love the game so much they want to play again next year.\"\n  3. **The 24-Hour Rule**: Explain the mandatory cooling-off period for game-related concerns. No exceptions.\n  4. **The Communication Standard**: Define your **Single Source of Truth** (e.g., GameChanger, TeamSnap, or SportsEngine). Emphasize: *\"If it's not in the app, it doesn't exist.\"*\n  5. **The Call**: Hand out specific volunteer assignments (Scorekeeper, Snack Coordinator) on the spot.\n\n**The Coaching Why**: An un-managed parent group is a distraction. A managed parent group is a support system." 
  },
  "B1-S8": { 
    book: "Book I", section: "8. Parents", title: "8.2 The 24-Hour Rule", 
    content: "### 8.2 The \"24-Hour Rule\" Enforcement\n\n**The Goal**: To protect both the coach and the parent from making emotional, heat-of-the-moment decisions that could damage the team culture.\n\n**The Policy**: \nCoaches will not engage in any discussion regarding game-related frustrations (playing time, positions, specific plays) until **24 hours after the final out** of that game has been recorded.\n\n**Execution Guidelines**:\n- **On the Field**: If a parent approaches you immediately after a game with a concern, use this phrase: *\"I value your feedback, but out of respect for the 24-hour rule, I'd like to schedule a time to talk about this tomorrow afternoon. Let's touch base then.\"*\n- **The Exception**: Logistics (e.g., \"Johnny left his glove\") are always okay to discuss immediately.\n- **The Meeting**: Once 24 hours have passed, the meeting should be brief, private, and focused on the solution, not the blame.\n\n**The Coaching Why**: Baseball is an emotional game. By mandating a \"cooling-off\" period, we ensure that conversations are grounded in logic and the best interest of the child, rather than the score of a single game." 
  },
  "B1-S9-P": { 
    book: "Book I", section: "9. Pathways", title: "9.2 Pitching Pathway", 
    content: "### 9.2 The \"Arm Care\" Pitcher Progression\n\n**The Goal**: To develop as many confident arms as possible by removing the fear of walks and focusing on mechanics over outcomes.\n\n**The Division Pathway**:\n- **AA (Foundations)**: Introduce the mound. **\"Coach Rescue\"** is the standard. If a player throws 4 balls, the coach enters to finish the at-bat. This prevents \"Walk Marathons\" and keeps the defense engaged.\n- **AAA (Accountability)**: Transition to **Full Kid Pitch**. No rescue. Pitchers learn to navigate a full at-bat. Focus: 100% on the Balance Point.\n- **Minors (Defense)**: Advanced mechanics and **Pitcher Fielding Practice (PFP)**. The pitcher becomes the \"5th Infielder\" on bunts and comebackers.\n- **Majors (Strategy)**: Full LLI tournament rules and advanced pitch-calling. Introduction of situational placement.\n\n**The Coaching Why**: Pitching is a skill, not a position. Every child should be given the foundation to learn it without the shame of throwing a walk." 
  },
  "B1-S11": { 
    book: "Book I", section: "11. End-of-Season", title: "11.1 The Speech Template", 
    content: "### 11.1 The \"Growth-First\" Closing Speech\n\n**The Goal**: To leave players with a permanent sense of accomplishment and pride, regardless of the season's win/loss record.\n\n**The Execution**:\n- **Setting**: Hold this in center field immediately following your final game. No parents should be in the huddle yet; this is for the players only.\n- **The 4-Part Script**:\n  1. **The Transformation**: *\"I want you to look at your teammate next to you. Think about how much better they are today than on the first day in the cold rain. You did that for each other.\"*\n  2. **The Effort**: *\"I am proud of your grit. We didn't just play baseball; we learned how to compete.\"*\n  3. **The Personal Moment**: Share one specific, tiny mechanical improvement you saw in each player (e.g., \"Johnny, you hit the cutoff man every time today.\").\n  4. **The Farewell**: *\"You will always be a [Team Name]. See you next season.\"*\n\n**The Coaching Why**: The final 3-minutes of your season will determine if a child signs up again next year. Make it about their growth, not the score." 
  },
  "B1-S12": { 
    book: "Book I", section: "12-15. All-Stars", title: "The All-Star Addendum", 
    content: "### The All-Star \"Excellence\" Addendum\n\n**The Goal**: To transition from a \"Development First\" mindset to a \"Performance First\" tournament culture while maintaining athlete integrity.\n\n**The Three Pillars**:\n1. **The SACRIFICE Pact**: *\"For the next 4 weeks, this team is your primary commitment. Vacations, other sports, and social events must be scheduled around our games.\"* Any breach of this pact is grounds for removal from the tournament roster.\n2. **The CBO Offensive Power**: Since LLI mandates a **Continuous Batting Order**, your 10th, 11th, and 12th hitters are just as crucial as your leadoff. Your job is to build a lineup that \"never dies.\" Even if a player is not in the starting defensive nine, they must be 100% engaged as an offensive threat.\n3. **The Defensive Nine**: While everyone bats, only nine play defense. Identify your most reliable defensive core for big moments and prepare your bench players for specific \"closer\" roles or situational defensive replacements.\n4. **The Zero-Tolerance Culture**: Any ejection of a player, coach, or parent for sportsmanship-related issues is an immediate disqualification for the remainder of the tournament.\n\n**The Coaching Why**: All-Stars is a reward for elite effort. You owe it to the players to provide an environment of high-standards and maximum competitive focus." 
  },

  // --- BOOK II/III: THE SKILLS & DRILLS (MERGED & AUDITED) ---
  "B2-S2-1": {
    book: "Book II/III", section: "2. Practice Planning", title: "2.1 The \"Split-Squad\" Plan (Full Field)",
    content: "### 2.1 The \"Split-Squad\" Plan (Full Field - 120 Minutes)\n\n**The Goal**: To maximize touches and eliminate \"standing around\" by splitting the staff and the field into two distinct Work Zones.\n\n**The Schedule**:\n- **0:00-0:15 (Warm-up)**: Dynamic stretching and \"Structured Throwing\" (Show them your number!).\n- **0:15-0:55 (The Circuit)**: Split Group A (Infield/Battery) and Group B (Outfield/Hitting). Swap after 20 mins.\n- **0:55-1:10 (Team Defense)**: Focus on Cutoffs & Relays (7.2) or Rundowns (3.4).\n- **1:10-1:45 (Situational Scrimmage)**: Live BP with a specific mission (Runner on 2nd, 1 out).\n- **1:45-2:00 (The Finisher)**: Competitive Cauldron (10.2).\n\n**The Golden Rule**: **Divide and Conquer.** One coach at home plate, one coach in the outfield gap.\n\n**The Coaching Why**: Large rosters lead to \"player drift.\" Splitting the squad halves the wait time and doubles the active development."
  },
  "B2-S2-2": {
    book: "Book II/III", section: "2. Practice Planning", title: "2.2 The \"Grass-Only\" Plan (Wet Field)",
    content: "### 2.2 The \"Grass-Only\" Plan (No Infield Access - 120 Minutes)\n\n**The Goal**: To maintain highly productive training even when the dirt is occupied or wet.\n\n**The Schedule**:\n- **0:00-0:15 (Warm-up)**: Dynamic stretching and \"Crossover Lead\" (4.3) practice.\n- **0:15-1:00 (Outfield Specialization)**: Outfield Star (4.1), Gap Communication (4.2), and Sliding (4.4).\n- **1:00-1:45 (Battery & Hitting)**: Pitchers and catchers work \"Balance Point\" (5.1) and \"Towel Drill\" (5.2) on the grass. Hitters work \"The Net Station\" (6.2).\n- **1:45-2:00 (Relay Races)**: High-speed conditioning/baserunning to finish.\n\n**The Golden Rule**: **The Field is Still Open.** Don't cancel because the dirt is wet; the grass is where games are often won or lost.\n\n**The Coaching Why**: Mastery of tracking, sliding, and mechanical power are \"non-dirt\" skills that separate elite teams from average ones."
  },
  "B2-S2-3": {
    book: "Book II/III", section: "2. Practice Planning", title: "2.3 The \"Cage Session\" (Indoor Facility)",
    content: "### 2.3 The \"Cage Session\" (90-Minute Indoor Facility)\n\n**The Goal**: To maximize mechanical ROI in a high-cost/limited-space facility (e.g., DBat).\n\n**The Management Tip**: Indoor time is expensive and often paid out of pocket. For heavy rain-out seasons, a **$10 per event contribution** from families is a common standard to help offset the facility cost.\n\n**The Schedule (90-Minute Clock)**:\n- **0:00-0:15 (Logistics)**: Dynamic stretch and \"Shadow Pitching\" (5.1) **before the paid time starts** (in the lobby or outside).\n- **0:15-0:55 (The \"Divider Up\" Circuit)**: Pull the divider to create one large field-space.\n  - **Zone 1 (Handles)**: Half-team works \"Short Fungo\" (3.3) for picking-work/soft-hands.\n  - **Zone 2 (The Net)**: Other half-team hit \"Tee & Soft Toss\" (6.2).\n- **0:55-1:25 (The Battery Split)**: Cages 1/2 for Live BP/Tracking (6.1). Bullpen for \"Balance Point\" (5.1) and \"Blocking\" (5.4).\n- **1:25-1:30 (Chalk Talk)**: Mental Game \"10-Second Rule\" (10.1) while cleaning up.\n\n**The Golden Rule**: **Never \"Just Stand There.\"** In a cage, if you aren't hitting, you are tracking the pitcher's release.\n\n**The Coaching Why**: Indoor time allows for a 1:1 ball-to-player ratio that is impossible on a massive grass field."
  },
  "B2-S3-1": { 
    book: "Book II/III", section: "3. Infield Drills", title: "3.1 Momentum Fielding", 
    content: "### FIELD GUIDE (Quick Execution)\n- **Objective**: Teach players to attack the ball and create momentum.\n- **Execution**: Three-cone triangle. Charge the rolled ball, field it out front, and walk through.\n- **Cue**: **\"Alligator Hands, Butt Down!\"**\n\n---\n### THE MANUAL (Deep Why)\n**Coaching Why**: Prevents \"flat-footed\" fielding. It teaches the player to 'read' the hop rather than let the hop read them." 
  },
  "B2-S3-2": { 
    book: "Book II/III", section: "3. Infield Drills", title: "3.2 4-Corner Flip", 
    content: "### FIELD GUIDE (Quick Execution)\n- **Progression**: 1) Soft/High Flip (Short Sq). 2) Firm/Fast Flip (Large Sq).\n- **Cue**: **\"Flip and Follow!\"** (Glove hand stays back to clear the lane).\n\n---\n### THE MANUAL (Deep Why)\n**Execution**: Round 1 (10ft) focuses on touch. Round 2 (20ft) focuses on Double Play speed." 
  },
  "B2-S3-3": {
    book: "Book II/III", section: "3. Infield Drills", title: "3.3 Short Fungo Drill",
    content: "### 3.3 The \"Rapid-Fire\" Short Fungo (Ball Management Method)\n\n**The Goal**: To achieve **maximum infield repetition** focusing purely on hand-eye coordination without the strain of throwing.\n\n**The Execution**:\n- **Context**: Ideal for a coach with a small ball bag (25-30 balls).\n- **Setup**: One coach/parent kneels 15 feet in front of a line of 3 players. A second group of 3 players stands 15 feet *behind* the first group.\n- **The Drill (Phase A)**: Coach hits/rolls 25 rapid-fire grounders to the first player in line. The player fields and drops the ball at their feet.\n- **The Shag (Phase B)**: Once the bag is empty (25 balls), the fielder rotates to the back. The 3 players behind immediately \"pounce\" on the balls and reload the coach's bag.\n\n**The Rotation Rule**: No player is allowed to stand still. You are either the **Fielder** (working hands) or the **Shagger** (reloading the \"inventory\").\n\n**The Coaching Why**: By removing the throw, we isolate the fundamental of \"See the ball into the glove.\" This drill turns a \"wait for the ball\" practice into a 2-minute \"High-Intensity Circuit\" that only requires 25-30 balls and zero down-time."
  },
  "B2-S3-4": { 
    book: "Book II/III", section: "3. Infield Drills", title: "3.4 Continuous Rundown", 
    content: "### 3.4 The \"Pickle\" (Continuous Rundown)\n\n**The Goal**: To achieve the out in **two throws or less** while preventing the runner from advancing to the lead base.\n\n**The Execution (Dart & Lane Method)**:\n- **Running Path**: Pick a lane (left or right) of the runner. Never run directly behind them, as the runner's body blocks the throwing path.\n- **The \"Go\"**: The fielder with the ball sprints 100% full speed at the runner to force them to commit to the lead base.\n- **The Dart Throw**: Arm up with the elbow at 90 degrees. No wind-up. Throw the ball like a dart once the next fielder calls \"NOW!\".\n- **The Follow**: After the throw, the fielder follows their ball to the next bag to replace the fielder who just received it.\n\n**The \"Standard\" Defensive Call**:\n- **\"BALL! BALL! BALL!\"**: The fielder without the ball must call for it loud and early when they want the throw.\n\n**The Coaching Why**: Most rundowns fail because of \"lazy runs\" or multiple throws. One hard sprint and one dart throw are all you need." 
  },
  "B2-S3-5": { 
    book: "Book II/III", section: "3. Infield Drills", title: "3.5 First-and-Third Defense", 
    content: "### 3.5 \"First-and-Third\" Defensive Situations\n\n**The Goal**: To present a disciplined defense that forces the runner at 1st to stay put, or caught in a pickle, without conceding 3rd base.\n\n**The Primary Options**:\n1. **The Pump Fake**: Catcher catches the strike, looks at 3B to freeze the runner, then hard-fakes a throw to 2B. If the runner at 3B breaks, throw to the 3rd Baseman.\n2. **The \"Cut-Off\" play**: Catcher throws to 2B, but the Shortstop or 2nd Baseman \"crashes\" inside the infield to cut the ball and immediately check the runner at 3rd base.\n3. **The Snap-to-Third**: Catcher immediately throws to 3B to catch a \"lazy\" runner off their lead. Requires a pre-determined sign.\n\n**Division Adjustments**:\n- **AA/AAA**: Focus only on the \"Long Throw\" to 2nd base. Don't worry about the double-steal; get the experience of the big throw.\n- **Minors/Majors**: Master the \"Pump Fake\" as the default play.\n\n**The Coaching Why**: First-and-Third is where most youth runs are conceded. A defense that knows their \"Cut\" spots is a defense they cannot run on." 
  },
  "B2-S3-6": {
    book: "Book II/III", section: "3. Infield Drills", title: "3.6 The Everyday Infield Fungo",
    content: "### 3.6 The \"Everyday\" Infield Fungo\n\n**The Goal**: To achieve **maximum infield repetition** in minimum time. This drill builds muscle memory for reading the ball off the wooden bat.\n\n**The Execution (The Round of 5)**:\n- **Setup**: One coach at home plate. Players at their standard defensive depth. Extra balls at the mound.\n- **The Drill Sequence**:\n  1. **To 3rd Base**: Charge, field, throw to 1B.\n  2. **To Shortstop**: Charge, field, throw to 1B.\n  3. **To 2nd Base**: Charge, field, throw to 1B.\n  4. **The Turn**: To 1st Base/2B/SS to practice turning a Double Play feed.\n  5. **Bunt Defense**: Coach rolls a bunt. Catcher pounces and throws to 1B.\n\n**The \"Standard\" Pace**:\n- **The Bucket Rule**: If a ball is missed, do not chase it! The coach immediately hits the next ball. A staff member or parent cleans the path only after the full round of 5 is finished.\n\n**The Coaching Why**: We don't practice until we get it right; we practice until we can't get it wrong. Structure prevents players from standing around." 
  },
  "B2-S4-1": {
    book: "Book II/III", section: "4. Outfield & Baserunning", title: "4.1 Outfield Star Drill",
    content: "### 4.1 The \"Outfield Star\" Full-Field Cycle\n\n**The Goal**: To train an outfielder to track and catch a fly ball in every game-possible scenario (overhead, glove side, backhand, and charge) without ever breaking their stride.\n\n**The Execution (Coach-Lob Method)**:\n- **Setup**: Visualize a large 5-point star on the field. Line of players starts at the coach.\n- **The Drill**: On \"GO!\", the player sprints toward the first star-tip. The coach **underhand lobs** the ball high into the air to **lead** the player into the catch.\n- **The 5-Point Cycle**:\n  1. **Tip 1 (Overhead)**: Run back, catch over the shoulder.\n  2. **Tip 2 (Glove Side Low)**: Angle for a lower-trajectory catch.\n  3. **Tip 3 (Backhand)**: Cross over and reach for a backhand catch.\n  4. **Tip 4 (Glove Hand Mid)**: Move horizontally (gap coverage).\n  5. **Tip 5 (The Crash)**: Charge full speed toward the infield to catch a shallow pop-up.\n\n**The Golden Rule**: **Never Backpedal.** We track with our eyes and move with our feet. Trust the lob and run into the ball.\n\n**The Coaching Why**: Underhand lobs allow for 100% accuracy from the coach. This removes the variable of \"bad hits\" and focuses the player entirely on their footwork and catch-paths."
  },
  "B2-S4-2": {
    book: "Book II/III", section: "4. Outfield & Baserunning", title: "4.2 Gap Communication",
    content: "## 4.2 Gap Communication (Turn, Locate, & Support)\n\n**The Goal**: To train an outfielder to turn, run to a spot, and locate a fly ball in the air while maintaining high-speed communication to avoid collisions.\n\n**The Execution**:\n- **Setup**: Place two markers (buckets or gloves) 10 feet apart. Two players start **between** the markers, facing the coach.\n- **The Turn**: On \"GO!\", both players turn and run **around the outside** of their respective markers, heading deep into the gap.\n- **The \"Blind\" Locate**: As they turn, the coach lobs a high pop-fly. **Crucial**: Players must not watch the coach; they must make their turn first and only \"find\" the ball once they are in their running path.\n- **The Communication**: One player calls **\"BALL! BALL! BALL!\"** loud and early.\n- **The Support**: The second player immediately peels off to back up the catcher and directs the play (e.g., \"Hit the cutoff!\").\n\n**The Coaching Why**: This simulates a ball hit over a player\'s head. It teaches them to run to a spot first, find the ball second, and trust their teammate\'s voice."
  },
  "B2-S4-3": {
    book: "Book II/III", section: "4. Outfield & Baserunning", title: "4.3 The Cross-Plate Break",
    content: "## 4.3 The \"Cross-Plate Break\" (First Step Explosiveness)\n\n**The Goal**: To maximize a baserunner\'s explosive first step on a steal or a secondary lead return by using a hard crossove mechanic.\n\n**The Execution**:\n- **Setup**: A runner at 1st base. Pitcher is in the stretch (coach or player).\n- **The Secondary Lead**: On the pitch, the runner takes two aggressive **shuffle-shuffles** (keeping their chest square to the plate).\n- **The Break (Steal or Advance)**: If the ball is hit or the steal is called, the runner plants their **left foot hard** and drives their **right knee** across their body in one explosive motion toward the target base.\n- **The Return**: If the ball is not put in play, the runner must sprint **immediately and vertically** back to the bag. **Crucial**: NO \"LAZY RETURSS\". You are either going to the next base or sprinting back to safety.\n\n**The Coaching Why**: Most pick-offs happen because of a lazy return. By teaching the \"Crossover Drive,\" we give players a 1-step advantage over the throw."

  },
  "B2-S4-4": {
    book: "Book II/III", section: "4. Outfield & Baserunning", title: "4.4 Sliding (Figure 4)",
    content: "## 4.4 The \"Figure 4\" Sliding Progression (Safety & Confidence)\n\n**The Goal**: To build a player\'s confidence and muscle memory for a safe, bent-leg slide while strictly enforcing the **No Head-First** safety rule.\n\n**The Execution (The 4-Stage Progression)**:\n- **Stage 1 (Grass Sit)**: Players sit on the grass and form a \"Figure 4\" with their legs (one leg-tucked under the other). Hands are up like they are \"holding groceries\" to protect the wrists.\n- **Stage 2 (The Glute Glide)**: From a walking start, players lower themselves into the Figure 4 and glide on the grass to feel the contact.\n- **Stage 3 (The Cardboard Slide)**: Lay down a long sheet of cardboard on the grass. This removes friction and \"road rash\" fear, allowing players to practice at full speed.\n- **Stage 4 (Dirt Finish)**: Finally, transition to the sliding pit or basepath for the real dirt slide.\n\n**The Golden Rules**:\n 1. **NEVER HEAD FIRST**: Strictly illegal in youth ball. Hands stay up.\n 2. **Tuck the Chin**: Keep the head up and chin tucked to avoid whipping the head back.\n\n**The Coaching Why**: Sliding is 90% confidence. Using the cardboard-on-grass method removes the fear of pain, allowing the player to focus purely on the \"Figure 4\" muscle memory."
  },
  "B2-S5-1": {
    book: "Book II/III", section: "5. The Battery Circuit", title: "5.1 The Balance Point",
    content: "### 5.1 The Balance Point (Pitching Stability)\n\n**The Goal**: To achieve **perfect internal balance** at the peak of the delivery, preventing the pitcher from \"falling\" toward the plate.\n\n**The Execution**:\n- **The Peak**: Lift the lead knee to a minimum of 90 degrees. The lift must be straight up, not swinging outward.\n- **The 3-Second Freeze**: Once the knee is lifted, the pitcher must **HOLD for 3 full seconds** without wobbling. Their head must remain dead-center over their back leg.\n- **The Cue**: **\"Stay Tall, Stay Strong.\"** Imagine a string pulling you up from the top of your hat.\n\n**The Coaching Why**: Most mechanical breakdowns happen because a pitcher rushes their delivery. By freezing at the balance point, we force the athlete to find their \"center\" before the explosive downward move."
  },
  "B2-S5-2": {
    book: "Book II/III", section: "5. The Battery Circuit", title: "5.2 The Towel Drill",
    content: "### 5.2 The \"Towel Drill\" (Mechanical Extension)\n\n**The Goal**: To achieve **maximum extension** and a consistent release point without the wear and tear of throwing a real baseball.\n\n**The Execution**:\n- **Setup**: The pitcher grips a small hand towel between their index and middle fingers (simulating a ball). Place a target (a chair or teammate) roughly 2 feet *beyond* the pitcher\'s normal stride length.\n- **The Delivery**: Go through the full pitching motion with intent.\n- **The Strike**: The goal is to \"flick\" the towel so it thumps the target at the peak of the extension.\n- **The Follow-Through**: Ensure the front leg stays firm and the chest finishes over the front knee.\n\n**The Coaching Why**: This is the ultimate \"arm care\" drill. It allows for high-speed mechanical repetitions without the stress of holding and releasing a ball, while forcing the pitcher to \"reach\" for their strike zone."
  },
  "B2-S5-3": {
    book: "Book II/III", section: "5. The Battery Circuit", title: "5.3 Pitcher Fielding Practice (PFP)",
    content: "### 5.3 Pitcher Fielding Practice (PFP)\n\n**The Goal**: To ensure pitchers remain active defenders and transition seamlessly from their \"Follow-Through\" to a \"Fielding Stance.\"\n\n**The Execution**:\n- **Scenario A (The Come-Backer)**: Pitcher goes through a dry motion. Coach hits a grounder directly at the mound. The pitcher must square up and field cleanly.\n- **Scenario B (Covering 1B)**: Coach hits a grounder to the 1st Baseman. The pitcher must immediately sprint toward 1B, \"arc\" their path, and receive the flip while stepping on the bag.\n- **Scenario C (The Bunt)**: Coach rolls a bunt. The pitcher pounces, clears the ball with their glove hand, and makes a strong \"Athletic Pose\" throw to 1B.\n\n**The Coaching Why**: Often, a pitcher stops being a defender after they release the ball. This drill reinforces that they are the **5th Infielder**. Mastering PFP prevents the most common \"free bases\" in youth baseball."
  },
  "B2-S5-4": {
    book: "Book II/III", section: "5. The Battery Circuit", title: "5.4 Blocking Progression",
    content: "### 5.4 The \"Blocking\" Progression (The Total Seal)\n\n**The Goal**: To train catchers to physically and mentally \"seal\" the 5-hole and absorb the energy of a wild pitch, keeping the ball directly in front of them.\n\n**The Execution (The 3-Stage Progression)**:\n- **Stage 1 (No Glove / Chest Absorption)**: Catcher is in a secondary stance (no glove). Coach lobs a soft ball. The catcher moves to block, tucking their chin and letting the ball hit their chest protector and drop straight down.\n- **Stage 2 (Glove Down / The 5-Hole Seal)**: Now add the glove. The catcher practice **jamming** the glove into the dirt between their knees. The glove must physically touch the ground to seal the gap.\n- **Stage 3 (Full Gear / Live Block)**: Full equipment. Coach throws live, controlled balls in the dirt. The catcher must react, block, and then \"pounce\" to prevent runners from advancing.\n\n**The Golden Rule**: **Glove First, Dirt Second.** The glove must hit the ground before the ball arrives. Tucking the chin protects the neck and ensures the catcher \"looks\" the ball into their body.\n\n**The Coaching Why**: Blocking is about being a \"Wall.\" This progression removes the fear of the ball and builds the mechanical habit of sealing the plate before the ball ever makes contact."
  },
  "B2-S5-5": {
    book: "Book II/III", section: "5. The Battery Circuit", title: "5.5 Pop-Time Footwork",
    content: "### 5.5 \"Pop-Time\" Footwork (The Replacement & Drive)\n\n**The Goal**: To achieve the fastest possible transfer from catch to throw on a steal attempt using efficient lower-body mechanics.\n\n**The Execution**:\n- **The \"Replacement\" Step**: As the ball enters the glove, the catcher quickly **replaces** their front foot\'s position with their back foot. This automatically aligns the shoulders with 2nd base.\n- **The Transfer**: Bring the ball to the \"Ear\" immediately. Do not \"wind up\" or drop the hand below the shoulder.\n- **The Throw**: Drive off the back leg and fire a low, \"frozen rope\" toward the target. Aim for the pitcher\'s head-height to keep the trajectory flat.\n- **The Long Hop**: Intentionally aim to bounce the ball 10-15 feet in front of the bag. A \"Long Hop\" is much easier to field than a ball that arrives at eye-level or sails high.\n\n**The Coaching Why**: Pop-time is won with the feet, not just the arm. Efficiency in the \"Replacement\" step eliminates the need for extra strides, saving crucial tenths of a second."
  },
  "B2-S6-1": {
    book: "Book II/III", section: "6. Hitting Fundamentals", title: "6.1 Five Core Components",
    content: "### 6.1 The \"Core 5\" Hitting Mechanics\n\n**The Goal**: To build a repeatable, powerful, and balanced swing by mastering the five sequential phases of the movement.\n\n**The Mechanical Flow**:\n1. **The Stance (Balance)**: Feet slightly wider than shoulders, knees athletic. Weight is on the \"inner half\" of the feet.\n2. **The Stride (The Load)**: A soft, controlled step toward the pitcher. The head stays still while the hands move back slightly to create \"separation.\"\n3. **The Rotation (The Drive)**: The back knee drives down and in (the \"Engine\"). Power is generated from the hips, not just the arms.\n4. **The Connection (The Rail)**: The knob of the bat leads directly to the ball. Hands stay \"inside\" the ball to create a short, compact path.\n5. **The Extension & Finish**: Arms reach full extension at contact. The swing finishes high and balanced on a firm front leg.\n\n**The Golden Rule**: **Still Head, Quiet Eyes.** If the head moves, the ball moves. The head must remain the \"center of the universe\" throughout the entire swing.\n\n**The Coaching Why**: Most hitting slumps are caused by \"lunging\" or \"arm-swinging.\" By isolating these 5 components, we can identify exactly where a player is losing their power or balance."
  },
  "B2-S6-2": {
    book: "Book II/III", section: "6. Hitting Fundamentals", title: "6.2 The Net Station (Tee & Soft Toss)",
    content: "### 6.2 The Net Station (Tee & Soft Toss)\n\n**The Goal**: To achieve **perfect muscle memory** by removing the complexity of a live pitcher and focusing purely on the contact point.\n\n**The Execution**:\n- **Part A (The Tee)**: Position the tee so the ball is over the center of the plate at belt height. Drive 10 balls straight into the center of the net, focusing purely on the **Core 5** mechanics.\n- **Part B (Soft Toss)**: A partner kneels safely at a 45-degree angle. They toss the ball into the hitting zone. The hitter must react, keep their head still, and maintain a compact path.\n\n**The Golden Rule**: **Contact Point Discipline.** On the tee, the ball should be just in front of the front foot. For soft toss, wait for the ball to enter the \"Window\"—don\'t lunge for it.\n\n**The Coaching Why**: Every elite hitter uses the tee. It is the only way to isolate mechanical leaks without the distraction of a moving pitch. If you can\'t hit it off the tee correctly, you won\'t hit it in the game."
  },
  "B2-S6-3": {
    book: "Book II/III", section: "6. Hitting Fundamentals", title: "6.3 Competitive Situational Scrimmage",
    content: "### 6.3 Competitive Situational Scrimmage\n\n**The Goal**: To bridge the gap between \"Practice Hitting\" and \"Game Hitting\" by introducing live situational pressure and decision-making.\n\n**The Execution**:\n- **Setup**: Full defense in the field. A live pitcher (coach or player). Hitter enters the box with a pre-set scenario (e.g., \"Runner on 2nd, 1 out, down by 1\").\n- **The \"Job\"**: The hitter\'s success is measured by the **result**, not the quality of the contact. Driving a runner home from 3rd with a groundout is a \"Win.\"\n- **The Competitive Scoring**: Award points for execution: 1 point for moving a runner, 2 points for a successful bunt, 3 points for a base hit that scores a run.\n\n**The Golden Rule**: **Know the Job.** Before stepping into the box, the hitter must vocally state the mission (e.g., \"I\'m hitting to the right side\"). If they can\'t state the mission, they aren\'t ready to hit.\n\n**The Coaching Why**: Hitting in a vacuum is easy. Hitting with the game on the line is a mental skill. This drill builds the \"Situational IQ\" needed to stay cool when the lights are on."
  },
  "B2-S7-1": {
    book: "Book II/III", section: "7. Team Defense", title: "7.1 Split-Squad Fungo",
    content: "### 7.1 The \"Split-Squad\" Fungo Routine (High Efficiency)\n\n**The Goal**: To maximize defensive repetitions for both infielders and outfielders simultaneously, eliminating the \"standing around\" time typical of full-team defense drills.\n\n**The Execution**:\n- **Station A (Infield Mastery)**: One coach at home plate hitting to the infield. Focus on \"Round of 5\" repetitions. All throws go to 1B.\n- **Station B (Outfield Tracking)**: A second coach (or parent) in the shallow outfield lobbing or hitting to the outfielders in the gaps. Focus on \"Tracking and Communication.\"\n- **The Bucket Rule**: Use the bucket system for both stations. No balls are thrown back to the coaches until the bucket is empty. This maintains a rapid-fire pace.\n\n**The Golden Rule**: **Divide and Conquer.** By splitting the staff and the field, you halve the wait time and double the \"touches\" for every player.\n\n**The Coaching Why**: Large rosters are the enemy of development. Breaking the team into two active squads keeps everyone engaged and ensures that \"Practice\" feels like \"Work.\""
  },
  "B2-S7-2": {
    book: "Book II/III", section: "7. Team Defense", title: "7.2 The String Drill",
    content: "### 7.2 The \"String Drill\" (Cutoffs & Relays)\n\n**The Goal**: To achieve **perfect defensive alignment** on balls hit to the outfield, ensuring the cutoff man, the ball, and the target base are in a perfectly straight line.\n\n**The Execution**:\n- **The Setup**: Position a full defense. Anchor a long rope or \"string\" at the target base (2B, 3B, or Home).\n- **The Rep**: Coach hits a ball into the gap. Outfielders retrieve it while the cutoff man (SS or 2B) sprints into position.\n- **The \"Freeze\"**: Once the cutoff man is set, the coach yells **\"FREEZE!\"** and pulls the string taut from the outfielder\'s hand to the target base.\n- **The Adjustment**: If the cutoff man is not directly under the string, they are out of alignment. Physically move them until the line is a \"Laser.\"\n\n**The Golden Rule**: **Hands Up, Turn Glove-Side.** The cutoff man must be a big target. They catch and turn toward their glove side to maintain momentum toward the next base.\n\n**The Coaching Why**: Most relay errors are alignment errors, not throwing errors. By using a literal \"String,\" we train the players to visualize the direct line of the play. Seconds are saved when the throw doesn\'t have to curve around a misplaced fielder."
  },
  "B2-S7-3": {
    book: "Book II/III", section: "7. Team Defense", title: "7.3 Bunt Defense",
    content: "### 7.3 Bunt Defense & Pop-Fly Priority\n\n**The Goal**: To establish a rigid communication hierarchy for both bunt coverage and pop-fly protection, ensuring every ball is claimed without hesitation or collision.\n\n**The Execution**:\n- **Bunt Coverage (The Boss)**: The Catcher is the \"Chief of Defense\" for bunts. They must yell the direction of the play (e.g., \"ONE! ONE! ONE!\") because they are the only ones facing the entire field.\n- **Pop-Fly Priority**: When a ball is in the air, players must adhere to the **Priority Chain**:\n  1. **Outfield > Infield**: Outfielders own any ball they can reach while moving forward.\n  2. **SS/2B > 3B/1B**: Middle infielders have priority over the corners.\n  3. **Infield > Pitcher**: Pitchers should almost never catch a pop-up unless it\'s a dead-stop to avoid interference with the mound.\n\n**The Golden Rule**: **Louder is Better.** Don\'t just call it; scream it. Use three-word bursts (e.g., \"ME! ME! ME!\") to ensure the message is received.\n\n**The Coaching Why**: \"Who\'s got it?\" is the most dangerous question in baseball. By establishing a clear \"Chain of Command\" in practice, you remove the split-second hesitation that leads to dropped balls and collisions."
  },
  "B2-S10-1": {
    book: "Book II/III", section: "10. Mental Game", title: "10.1 The 10-Second Rule",
    content: "### 10.1 The \"10-Second\" Recovery Protocol\n\n**The Goal**: To provide players with a repeatable mental \"circuit breaker\" that prevents one mistake (like a strikeout or an error) from snowballing into a second or third mistake.\n\n**The Execution (The Reset Routine)**:\n1. **The Window**: After a failure, the player has exactly **10 seconds** to be frustrated. They can kick the dirt or squeeze their glove, but they must maintain their composure.\n2. **The \"Flash-Flush\"**: At the 10-second mark, the player performs a physical \"reset\" action—like adjusting their hat or wiping their hand across their jersey—to symbolize \"flushing\" the error.\n3. **The Pivot**: The player takes one deep breath and identifies the **Next Job** (e.g., \"Ready for the next grounder\").\n\n**The Golden Rule**: **EYES ON THE NEXT PLAY.** You are allowed to be human for 10 seconds, but you aren\'t allowed to let the past play beat you on the next pitch.\n\n**The Coaching Why**: Baseball is a game of failure. The best players aren\'t the ones who never fail; they are the ones who recover the fastest. This protocol normalizes the emotional response while providing a structured path back to focus."
  },
  "B2-S10-2": {
    book: "Book II/III", section: "10. Mental Game", title: "10.2 Competitive Cauldron",
    content: "### 10.2 The \"Competitive Cauldron\" (Pressure Inoculation)\n\n**The Goal**: To simulate the physical and mental effects of high-stakes game situations, training players to maintain their technique even when their heart rate increases.\n\n**The Execution**:\n- **The Setup**: During a standard scrimmage or drill, the coach yells **\"CAULDRON!\"** to instantly pause and reset the field.\n- **The Scenario**: The coach dictates a \"Win-or-Loss\" moment: *\"Bases loaded, 2 outs, bottom of the 6th, full count. If the ball stays in the infield, the defense wins. Hit it out, the offense wins.\"*\n- **The Intensity**: The play is run with 100% intensity. There is a clear winner and a clear loser for every rep.\n\n**The Golden Rule**: **Embrace the Beat.** We tell players that a racing heart isn\'t \"fear\"—it\'s \"fuel.\" Don\'t try to calm down; try to focus your energy on the **Next Job**.\n\n**The Coaching Why**: You can\'t teach \"clutch\" in a vacuum. You only learn to perform under pressure by experiencing it repeatedly in practice. This drill \"inoculates\" players against the shock of the big moment by making it a regular part of their training."
  },

  // --- UMPIRE OFFICE ---
  "U-C1": {
    book: "Umpire Office", section: "1. Core Clinic", title: "1.1 Timing & Authority",
    content: "### 1.1 Timing, Tone, & Verbal Presence\n\n**The Goal**: To establish absolute authority and clarity through assertive verbal and physical signals.\n\n**The Standard**:\n- **Verbal Precision**: A loud, crisp **\"STRIKE!\"** combined with a sharp \"hammer\" or \"wall-pound\" with the right hand.\n- **The Count**: Always show the count manually. **Left Hand = Balls**, **Right Hand = Strikes**. Never \"bump fists\" for a full count; raise 3 fingers on the left and 2 on the right.\n- **Brief & Loud**: Decisiveness eliminates arguments. Use short, high-volume bursts to command the field.\n\n**The Why**: Authority is about being **sure**. A decisive umpire who communicates clearly keeps the temperature of the game low and the pace high."
  },
  "U-C2": {
    book: "Umpire Office", section: "1. Core Clinic", title: "1.2 The Plate Meeting (Youth Umpire Standard)",
    content: "### 1.2 The Plate Meeting (Youth Umpire Standard)\n\n**The Goal**: To provide a youth umpire with a \"Command Script\" that ensures they remain the clinical authority of the game, regardless of the age of the managers.\n\n**The Command Script (The Protocol)**:\n1. **The Summons**: At 5 minutes before game time, the umpire stands at the plate and calls: *\"Managers to the plate with your lineups, please.\"*\n2. **The Introduction**: Shake hands with each manager. State your name and your partner\'s name clearly.\n3. **The Safety Vetting**: Ask: *\"Coaches, are all of your players in full uniform and is all equipment meeting the current safety standards?\"*\n4. **The Ground Rules**: Keep it brief. *\"Everything over the fence is a home run. Any ball that goes into the dugout is a dead-ball; we\'ll award a base from there.\"*\n5. **The Closing**: *\"Good luck to both teams. Let\'s have a fast, safe game. Play ball!\"*\n\n**The Golden Rule**: **Be Clinically Brief.** You aren\'t there to be friends with the managers; you are there to enforce the rulebook fairly. If a manager begins complaining or talking over you, use the phrase: *\"Thank you, coach. I have my ground rules set. Let’s get the game started.\"*\n\n**The Why**: The Plate Meeting is the \"Theater of Authority.\" A youth umpire who follows a rigid script projects confidence. If you start with a strong meeting, the managers are significantly less likely to argue with your calls during the game."
  },
  "U-G1": {
    book: "Umpire Office", section: "2. Mechanics", title: "2.1 The Slot & \"Opening the Gate\"",
    content: "### 2.1 The Slot & \"Opening the Gate\"\n\n**The Goal**: To maximize the view of the strike zone while staying safe and remaining \"invisible\" to the flow of play.\n\n**The Mechanics**:\n- **The Slot**: Position your chin with the catcher\'s **inside ear**. This provides a clear \"window\" to see the inside corner and the pitcher\'s release.\n- **The Lock**: Once the pitcher is set, \"Lock\" into your stance. Your head must remain a \"fixed point\" from release to catch.\n- **The Gate**: On a base hit, \"Open the Gate\" by stepping back and clearing the path for the catcher and the bat. Don\'t be an obstacle.\n\n**The Why**: If your head moves, the strike zone moves. Stability in the slot ensures a consistent \"box\" for the pitchers and hitters."
  },
  "U-G2": {
    book: "Umpire Office", section: "2. Mechanics", title: "2.2 Base Mechanics: Angle over Distance",
    content: "### 2.2 Base Mechanics: Angle over Distance\n\n**The Goal**: To position the base umpire for the highest-probability view of a play while remaining out of the path of ball and runner.\n\n**The Positions**:\n- **Position A**: Behind 1B (Bases empty). Used for the \"Force Out\" focus.\n- **Positions B/C**: Inside the diamond (Runners on). Used to get closer to tag plays and double-play turns.\n- **The Golden Rule**: **Angle Over Distance.** Being 25 feet away at a 90-degree angle is infinitely better than being 5 feet away looking at a runner\'s back. Always seek the \"Window\" where you can see the **ball**, the **base**, and the **runner** at once.\n\n**The Why**: Amateur umpires often chase the ball. Elite umpires \"let the play come to them\" by moving to the angle of the throw first."
  },
  "U-P1": {
    book: "Umpire Office", section: "3. Partner Synergy", title: "3.1 Partner Signals & Coverage",
    content: "### 3.1 Partner Signals & Coverage\n\n**The Goal**: To ensure 100% field coverage through non-verbal synchronization and explosive rotation between two umpires.\n\n**The Coverage**:\n- **The 1st-to-3rd Signal**: With a runner on 1st, the plate umpire leads the rotation to 3B on a base hit. This must be signaled to and \"echoed\" by the base umpire.\n- **The Timing Play**: Both umpires signal when a \"Time Play\" is imminent (third out vs. runner crossing home).\n- **The Takeover**: In a rundown, use the **Pat-on-Chest** signal and yell: *\"PARTNER, I\'VE GOT IT!\"* Eye contact is the only way to confirm a handover.\n\n**The Why**: A two-man crew is only as good as its communication. Without signals, you end up with two umpires watching the same bag while a runner cruises into another."
  }
};
